// Cart action types
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_UPDATE_QUANTITY = 'CART_UPDATE_QUANTITY';
export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS';

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';

export const CART_CALCULATE_PRICES = 'CART_CALCULATE_PRICES';
export const CART_APPLY_COUPON_REQUEST = 'CART_APPLY_COUPON_REQUEST';
export const CART_APPLY_COUPON_SUCCESS = 'CART_APPLY_COUPON_SUCCESS';
export const CART_APPLY_COUPON_FAIL = 'CART_APPLY_COUPON_FAIL';
export const CART_REMOVE_COUPON = 'CART_REMOVE_COUPON';

export const CART_GET_SHIPPING_RATES_REQUEST = 'CART_GET_SHIPPING_RATES_REQUEST';
export const CART_GET_SHIPPING_RATES_SUCCESS = 'CART_GET_SHIPPING_RATES_SUCCESS';
export const CART_GET_SHIPPING_RATES_FAIL = 'CART_GET_SHIPPING_RATES_FAIL';
export const CART_SELECT_SHIPPING_RATE = 'CART_SELECT_SHIPPING_RATE';

export const CART_CLEAR_ERROR = 'CART_CLEAR_ERROR';