// User action types
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_RESET = 'USER_LIST_RESET';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const USER_ADDRESS_LIST_REQUEST = 'USER_ADDRESS_LIST_REQUEST';
export const USER_ADDRESS_LIST_SUCCESS = 'USER_ADDRESS_LIST_SUCCESS';
export const USER_ADDRESS_LIST_FAIL = 'USER_ADDRESS_LIST_FAIL';

export const USER_ADDRESS_CREATE_REQUEST = 'USER_ADDRESS_CREATE_REQUEST';
export const USER_ADDRESS_CREATE_SUCCESS = 'USER_ADDRESS_CREATE_SUCCESS';
export const USER_ADDRESS_CREATE_FAIL = 'USER_ADDRESS_CREATE_FAIL';
export const USER_ADDRESS_CREATE_RESET = 'USER_ADDRESS_CREATE_RESET';

export const USER_ADDRESS_UPDATE_REQUEST = 'USER_ADDRESS_UPDATE_REQUEST';
export const USER_ADDRESS_UPDATE_SUCCESS = 'USER_ADDRESS_UPDATE_SUCCESS';
export const USER_ADDRESS_UPDATE_FAIL = 'USER_ADDRESS_UPDATE_FAIL';
export const USER_ADDRESS_UPDATE_RESET = 'USER_ADDRESS_UPDATE_RESET';

export const USER_ADDRESS_DELETE_REQUEST = 'USER_ADDRESS_DELETE_REQUEST';
export const USER_ADDRESS_DELETE_SUCCESS = 'USER_ADDRESS_DELETE_SUCCESS';
export const USER_ADDRESS_DELETE_FAIL = 'USER_ADDRESS_DELETE_FAIL';

export const USER_ADDRESS_SET_DEFAULT_REQUEST = 'USER_ADDRESS_SET_DEFAULT_REQUEST';
export const USER_ADDRESS_SET_DEFAULT_SUCCESS = 'USER_ADDRESS_SET_DEFAULT_SUCCESS';
export const USER_ADDRESS_SET_DEFAULT_FAIL = 'USER_ADDRESS_SET_DEFAULT_FAIL';

export const USER_SELLER_PROFILE_REQUEST = 'USER_SELLER_PROFILE_REQUEST';
export const USER_SELLER_PROFILE_SUCCESS = 'USER_SELLER_PROFILE_SUCCESS';
export const USER_SELLER_PROFILE_FAIL = 'USER_SELLER_PROFILE_FAIL';

export const USER_SELLER_PROFILE_UPDATE_REQUEST = 'USER_SELLER_PROFILE_UPDATE_REQUEST';
export const USER_SELLER_PROFILE_UPDATE_SUCCESS = 'USER_SELLER_PROFILE_UPDATE_SUCCESS';
export const USER_SELLER_PROFILE_UPDATE_FAIL = 'USER_SELLER_PROFILE_UPDATE_FAIL';
export const USER_SELLER_PROFILE_UPDATE_RESET = 'USER_SELLER_PROFILE_UPDATE_RESET';

export const USER_WISHLIST_REQUEST = 'USER_WISHLIST_REQUEST';
export const USER_WISHLIST_SUCCESS = 'USER_WISHLIST_SUCCESS';
export const USER_WISHLIST_FAIL = 'USER_WISHLIST_FAIL';

export const USER_WISHLIST_ADD_ITEM_REQUEST = 'USER_WISHLIST_ADD_ITEM_REQUEST';
export const USER_WISHLIST_ADD_ITEM_SUCCESS = 'USER_WISHLIST_ADD_ITEM_SUCCESS';
export const USER_WISHLIST_ADD_ITEM_FAIL = 'USER_WISHLIST_ADD_ITEM_FAIL';

export const USER_WISHLIST_REMOVE_ITEM_REQUEST = 'USER_WISHLIST_REMOVE_ITEM_REQUEST';
export const USER_WISHLIST_REMOVE_ITEM_SUCCESS = 'USER_WISHLIST_REMOVE_ITEM_SUCCESS';
export const USER_WISHLIST_REMOVE_ITEM_FAIL = 'USER_WISHLIST_REMOVE_ITEM_FAIL';

export const USER_CLEAR_ERROR = 'USER_CLEAR_ERROR';